# Common settings
# Game mode specific sections are needed too to apply these settings
[DEFAULT]
# D3D11 will be enabled in all games
rendering-backend = dx11
proton-directory = /usr/share/steam/compatibilitytools.d/proton-cachyos-slr

# Forbid Discord Rich Presence in multiplayer of ETS2
[ets2mp]
game-directory = /run/media/sab/Games/TruckersMP/ets2

# Even if there are no game specific settings for ATSMP,
# the empty section is needed if the user wants to apply the settings
# in the "[DEFAULT]" section
[atsmp]
game-directory = /run/media/sab/Games/TruckersMP/ats

# Game mode specific settings for ETS2 singleplayer
[ets2]

# Use custom game options only when starting singleplayer of ATS
[ats]
game-options = -mm_pool_size 600 -nointro -64bit
